FROM inn0kenty/pyinstaller-alpine:3.8 as builder
WORKDIR /app
COPY . .
RUN pip install .
RUN PATH="/pyinstaller:$PATH" pyinstaller docker-make.spec \
 && /app/dist/docker-make -v

FROM docker
RUN apk update \
 && apk add git
COPY --from=builder /app/dist/docker-make /docker-make
ENTRYPOINT ["/docker-make"]
